### PR TITLE
fix: incorrect context help message

### LINKED ISSUE #282: Incorrect context help message
#### Describe the bug
The help message for context is showing an incorrect context command `asyncapi context use mycontext`.

```
error locating AsyncAPI document: Specify what AsyncAPI file to be used.
These are your options to specify in the CLI what AsyncAPI file should be used:
 - You can provide a path to the AsyncAPI file: asyncapi <command> path/to/file/asyncapi
 - You can also pass a saved context that points to your AsyncAPI file: asyncapi <command> context-name
 - In case you did not specify a context that you want to use, the CLI checks if there is a default context and uses it. To set default context run: asyncapi context use mycontext
 - In case you did not provide any reference to AsyncAPI file and there is no default context, the CLI detects if in your current working directory you have files like asyncapi.json, asyncapi.yaml, asyncapi.yml. Just rename your file accordingly.
```

The file with the error: https://github.com/asyncapi/cli/blob/master/src/errors/context-error.ts

### PR DESCRIPTION
**Pull request by pranay202**
**Related issue(s)**

Resolves #282

### CODE REVIEW

**Comment by pranay202** [comment]
Hey @boyney123 @Souvikns @magicmatatjahu, can you please review my PR.

File: src/errors/context-error.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ export const NO_CONTEXTS_SAVED = `Specify what AsyncAPI file to be used.
 These are your options to specify in the CLI what AsyncAPI file should be used:
  - You can provide a path to the AsyncAPI file: asyncapi <command> path/to/file/asyncapi
  - You can also pass a saved context that points to your AsyncAPI file: asyncapi <command> context-name
- - In case you did not specify a context that you want to use, the CLI checks if there is a default context and uses it. To set default context run: asyncapi context use mycontext
+ - In case you did not specify a context that you want to use, the CLI checks if there is a default context and uses it. To set default context run: asyncapi context use defaultContext
  - In case you did not provide any reference to AsyncAPI file and there is no default context, the CLI detects if in your current working directory you have files like asyncapi.json, asyncapi.yaml, asyncapi.yml. Just rename your file accordingly.
```
Comment (Souvikns) [inline src/errors/context-error.ts:8]: I think we have to change message completely, Since this error is thrown when there is no context file created, It would be also nice to add steps on how to create context 

Something like this - 


```
No context has been set yet, 
To use a context as current you need to create one, follow these steps - 
 - Create a new context: asyncapi config context add <context-name> <file-path | URL>
 - Set this context as current: asyncapi config context use <context-name>
```

**Review by Souvikns — CHANGES_REQUESTED** [review]

File: src/errors/context-error.ts (hunk 1 above)
Comment (derberg) [reply src/errors/context-error.ts:8]: @pranay202 play a bit with the CLI to get the idea how these different options work

Comment (pranay202) [reply src/errors/context-error.ts:8]: Thank you for your reviews @Souvikns and @derberg. I will surely work on this and let you know with the PR.

Comment (pranay202) [reply src/errors/context-error.ts:8]: Can we have it like this -
```
No context has been set yet, 
To use a context as current you need to create one, follow these steps - 
 - Create a new context: asyncapi config context add <context-name> <file-path | URL>
 - Set this context as current: asyncapi config context use <context-name>
 - Try asyncapi --help to learn more about commands or go through the <a href="https://www.asyncapi.com/docs">docs</a>
```

Comment (Souvikns) [reply src/errors/context-error.ts:8]: Yeah looks fine to me 👍🏼

Comment (pranay202) [reply src/errors/context-error.ts:8]: Thank you for your reviews @Souvikns.

File: src/errors/context-error.ts [hunk 2]
```diff
@@ -1,11 +1,11 @@
...
-These are your options to specify in the CLI what AsyncAPI file should be used:
- - You can provide a path to the AsyncAPI file: asyncapi <command> path/to/file/asyncapi
- - You can also pass a saved context that points to your AsyncAPI file: asyncapi <command> context-name
- - In case you did not specify a context that you want to use, the CLI checks if there is a default context and uses it. To set default context run: asyncapi context use mycontext
- - In case you did not provide any reference to AsyncAPI file and there is no default context, the CLI detects if in your current working directory you have files like asyncapi.json, asyncapi.yaml, asyncapi.yml. Just rename your file accordingly.
+No context has been set yet, 
+To use a context as current you need to create one, follow these steps - 
+ - Create a new context: asyncapi config context add <context-name> <file-path | URL>
+ - Set this context as current: asyncapi config context use <context-name>
+ - Try asyncapi --help to learn more about commands.
```
Comment (Souvikns) [inline src/errors/context-error.ts:8]: @pranay202 sorry for pointing you in the wrong direction, I just ran the command in CLI to understand where this error is getting generated, and changing this error message wouldn't be possible because somehow CLI is printing this message when there is no context created and when the input is incorrect as well. I think we need to rework the error handling right now it is a mess. 

can you just write this 

```suggestion
These are your options to specify in the CLI what AsyncAPI file should be used:
 - You can provide a path to the AsyncAPI file: asyncapi <command> path/to/file/asyncapi
 - You can also pass a saved context that points to your AsyncAPI file: asyncapi <command> context-name
 - In case you did not specify a context that you want to use, the CLI checks if there is a default context and uses it. To set default context run: asyncapi config context use mycontext
 - In case you did not provide any reference to AsyncAPI file and there is no default context, the CLI detects if in your current working directory you have files like asyncapi.json, asyncapi.yaml, asyncapi.yml. Just rename your file accordingly.
```

Just changing the `asyncapi context use..` to `asyncapi config context use..` 

Also after this issue would you like to work on remodeling the error handing, I would love to help you with it?

**Review by Souvikns — CHANGES_REQUESTED** [review]

File: src/errors/context-error.ts (hunk 2 above)
Comment (pranay202) [reply src/errors/context-error.ts:8]: Sure. No worries, thank you guiding me!

**Review by Souvikns — APPROVED** [review]
Awesome 👍🏼. I think we can merge once @derberg approves.

File: src/errors/context-error.ts [hunk 3]
```diff
@@ -1,11 +1,10 @@
...
- - In case you did not specify a context that you want to use, the CLI checks if there is a default context and uses it. To set default context run: asyncapi context use mycontext
- - In case you did not provide any reference to AsyncAPI file and there is no default context, the CLI detects if in your current working directory you have files like asyncapi.json, asyncapi.yaml, asyncapi.yml. Just rename your file accordingly.
+export const NO_CONTEXTS_SAVED = `These are your options to specify in the CLI what AsyncAPI file should be used:
+- You can provide a path to the AsyncAPI file: asyncapi <command> path/to/file/asyncapi
+- You can also pass a saved context that points to your AsyncAPI file: asyncapi <command> context-name
+- In case you did not specify a context that you want to use, the CLI checks if there is a default context and uses it. To set default context run: asyncapi config context use mycontext
+- In case you did not provide any reference to AsyncAPI file and there is no default context, the CLI detects if in your current working directory you have files like asyncapi.json, asyncapi.yaml, asyncapi.yml. Just rename your file accordingly.
```
Comment (derberg) [inline src/errors/context-error.ts:7]:
```suggestion
export const NO_CONTEXTS_SAVED = `These are your options to specify in the CLI what AsyncAPI file should be used:
- You can provide a path to the AsyncAPI file: asyncapi <command> path/to/file/asyncapi.yml
- You can provide URL to the AsyncAPI file: asyncapi <command> https://example.com/path/to/file/asyncapi.yml
- You can also pass a saved context that points to your AsyncAPI file: asyncapi <command> context-name
- In case you did not specify a context that you want to use, the CLI checks if there is a default context and uses it. To set default context run: asyncapi config context use mycontext
- In case you did not provide any reference to AsyncAPI file and there is no default context, the CLI detects if in your current working directory you have files like asyncapi.json, asyncapi.yaml, asyncapi.yml. Just rename your file accordingly.
```

let us not forget about the URL 😄

**Review by derberg — APPROVED** [review]

**Comment by Souvikns** [comment]
We also have to update it here https://github.com/asyncapi/cli/blob/a6ba7e092620a90d2871a619516d230387efb535/src/commands/config/context/add.ts#L22

**Review by Souvikns — APPROVED** [review]
