### PR TITLE
fix: improve CLI messages and move them into separate file

### LINKED ISSUE #21: Turn CLI messages to constants
please create another followup issue to turn these messages into constants so we reuse them in components and tests, something like https://github.com/asyncapi/asyncapi-react/blob/master/library/src/constants.ts

no need to fix it now, not related to this pr

_Originally posted by @derberg in https://github.com/asyncapi/cli/pull/14#discussion_r666844302_

### PR DESCRIPTION
**Pull request by Souvikns**
**Description**
Turning CLI messages into constant so that it would be easy to update in the future. 

**Related issue(s)**
Resolves #21

### CODE REVIEW

**Comment by Souvikns** [comment]
## Breaking the help commands into different parts. 
Taking inspiration from `commander.js` we can divide every command to have top options and its subcommands. 
so the top-level command would look something like this. 

#### `asyncapi --help`
```
Usage: asyncapi [options] [command]

Options:
  -V, --version       output the version number
  -h, --help          display help for command

Commands:
  context [options]   Manage contexts
  validate [options]  validate spec file
```

#### `asyncapi context --help` 
```
Usage: asyncapi context [options] [command]

Store key-value pair of contexts and the CLI will load your contexts 
automatically making your commands shorter. 

Options:
  -h, --help          display help for command

Commands:
  list                list all saved contexts
  current             see current context
  use <context-name>  set the context as current context
  add <context-name> <spec-file-path>   add/update new context
  remove <context-name>  remove a context
```

#### `asyncapi validate --help`
```
Usage: asyncapi validate [options]

validate spec file

Options:
  -f, --file <spec-file-path>         Path of the spec file
  -c, --context <saved-context-name>  context name to use
  -w, --watch                         watch mode
  -h, --help                          display help for command

Example:
 $ asyncapi validate --file=./asyncapi.yml
 $ asyncapi validate  // if context is set. 
```

**Comment by derberg** [comment]
looks great, but remember, not in scope of this PR 😉 

> Store key-value pair of contexts and the CLI will load your contexts 
automatically making your commands shorter. 

we need also a sentence that explains what context is

> validate spec file

Rather `Validate an AsyncAPI file`

> Also I was thinking we should add an external link to the documentation of how CLI loads spec path automatically

I don't think it should be external. when I run `asyncapi validate` I don't want to see error that I have no contexts, I want to just get an info that I need to point to AsyncAPI file and a detailed explanation how I can do that, right there in the error, that I can use file flag with link to file, or context name with info how to get more help about context, or default context or default filename in CWD

**Comment by Souvikns** [comment]
@derberg I have converted all the error messages into constants and created a `Help` class to generate help messages as needed.

File: src/messages.tsx [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+      '-f, --file <spec-file-path>  Path of the spec file',
+      '-c, --context <saved-context-name>  Context name to use',
+      '-w, --watch  watch mode',
+      this._helpFlag
+    ]
+  }
+
+  private context: CommandHelp = {
+    name: 'context',
+    usage: 'asyncapi context [options] [command]',
```
Comment (derberg) [inline src/messages.tsx:47]:
```suggestion
    usage: 'asyncapi context [command] [options]',
```

File: src/messages.tsx [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+    shortDescription: 'Manage contexts',
+    flags: [
```
Comment (derberg) [inline src/messages.tsx:49]:
```suggestion
    longDescription: 'Context is what makes it easier for you to work with multiple AsyncAPI files. You can add multiple different files to a context. This way you do not have to pass --file flag with path to the file every time but just --context flag with reference name. You can also set a default context, so neither --file nor --context flags are needed.
    flags: [
```

+ enable support for `longDescription` as atm it is not consumed

**Review by derberg — COMMENTED** [review]
@Souvikns nice, looks super clean, just left 2 comments

File: src/help-message.ts [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+      }
+    }
+
+    return helpText;
+  }
+
+  showCommandHelp(command: CommandName) {
+    let helpText = '';
+    // eslint-disable-next-line security/detect-object-injection
+    const commandHelpObject = this.helpMessage.commands[command];
```
Comment (magicmatatjahu) [inline src/help-message.ts:78]:
```suggestion
    const commandHelpObject = this.helpMessage.commands[String(command)];
```

**Review by derberg — COMMENTED** [review]
what about messages from https://github.com/asyncapi/cli/blob/master/src/components/Context/contexterror.tsx ? 

ultimate goal should be you never have to do things like this in tests: `expect(lastFrame()).toMatch('No contexts saved yet.');` so basically never explicitly hardcode the message in the test but use a constant

File: src/help-message.ts (hunk 3 above)
Comment (Souvikns) [reply src/help-message.ts:78]: `const commandHelpObject = this.helpMessage.commands[String(command)];` wasn't working but 
`const commandHelpObject = this.helpMessage.commands[command as CommandName];`  did.

Comment (magicmatatjahu) [reply src/help-message.ts:78]: If you can remove the `eslint-disable...` by doing it, then change it with `as`

**Comment by Souvikns** [comment]
@derberg I have converted the error messages into constants. 

Some context commands have string responses like when a context is deleted. Shall I convert those into constant?

**Comment by derberg** [comment]
@Souvikns basically any message printed to the user must be a constant as it must be tested, thus it is used in code and tests, and should not be repeated. There are some tests for context and validation that are still using "hardcoded" messages, like `Error Thrown`, `Error in validation`, `context deleted successfully` or `File: ${file.getSpecificationName()} successfully validated!`

**Comment by Souvikns** [comment]
I was thinking of creating a complete class for responses, just like I did for the help message text.

**Comment by derberg** [comment]
For HelpMessage it makes sense as there is a lot of reusability, the other messages are pretty independent. Class would be an overhead imho

**Comment by Souvikns** [comment]
@derberg can we run the tests again, all the test cases are running in my local setup. 
image

**Comment by derberg** [comment]
@Souvikns look at the error:
```
Expected substring: "No contexts saved yet, run asyncapi --help to know more"
    Received string:    "home : /Users/runner/work/cli/cli/test/specification.yml
    code : /Users/runner/work/cli/cli/test/specification.yml"
```

looks like test picked up some old instance that has `.asyncapi` file with some old test data. I rerun, but might be it won't work.

**Comment by derberg** [comment]
Still some messages are there hardcoded:
- https://github.com/Souvikns/cli/blob/better-cli-messages/src/hooks/validation/hook.tsx#L13
- https://github.com/Souvikns/cli/blob/better-cli-messages/src/hooks/validation/hook.tsx#L17

**Comment by Souvikns** [comment]
Again the macos-tests are failing. 

```tsx
  test('return validation service errors when the validation has failed', async () => {
    ValidationServiceMock().makeReturn(ValidationResponse.createError({ detail: 'Error in validation' }));

    const useValidateResponse = await useValidate().validate(fileThatExistsValidationInput);
    expect(useValidateResponse.success).toBeFalsy();
    expect(useValidateResponse.errors[0]).toEqual('Error in validation');
  });
```

There are some test cases that are checking for error messages from the parser. Should we need to make these errors constants.

File: src/messages.tsx [hunk 4]
```diff
@@ -0,0 +1,20 @@
+export const NO_CONTEXTS_SAVED = 'No contexts saved yet, run asyncapi --help to know more';
+
+export const CONTEXT_NOT_FOUND = 'This context key does not exists.';
+
+export const KEY_NOT_FOUND = 'Key not found';
+
+export const DELETING_CURRENT_CONTEXT = 'You are tyring to delete a context that is currently in use.';
```
Comment (derberg) [inline src/messages.tsx:7]: spelling error and also context name should be in the message

`Context {CONTEXT_NAME} is set as current and cannot be removed`

File: src/messages.tsx [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+
+export const MISSING_CURRENT_CONTEXT = 'No context is set as current, please set a current context.';
```
Comment (derberg) [inline src/messages.tsx:9]: I don't think `MissingCurrentContextError` is ever used

File: src/messages.tsx [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+
+export const MISSING_ARGUMENTS = 'Missing arguments.';
```
Comment (derberg) [inline src/messages.tsx:11]: I don't think `MissingArgumentstError` is ever used

File: src/messages.tsx [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+
+export const NEW_CONTEXT_ADDED = 'New context added.';
```
Comment (derberg) [inline src/messages.tsx:13]: How about?

`New context added. \nYou can set it as your current context:\n      asyncapi context use {CONTEXT_NAME}\nYou can use this context when needed with --context flag`

**Review by derberg — COMMENTED** [review]
since we have now all the messages in one place I made some suggestions to make them sound better

File: src/messages.tsx (hunk 5 above)
Comment (Souvikns) [reply src/messages.tsx:9]: `MissingCurrentContextError` is used here https://github.com/asyncapi/cli/blob/2f69e066f00c1dcb8336b1f1f2d8aac09d23884b/src/hooks/context/hooks.tsx#L27

Comment (derberg) [reply src/messages.tsx:9]: oh, but such message should never be printed to the user. When user did not pass `file` or `context` option, and also did not specify a default context, we should look for default files in CWD, and if they are missing, we should print a nice message that explains possible options

Comment (derberg) [reply src/messages.tsx:9]: can be fixed with https://github.com/asyncapi/cli/issues/35 though

Comment (Souvikns) [reply src/messages.tsx:9]: Yeah I will be fixing this just after this PR.

File: src/messages.tsx (hunk 7 above)
Comment (Souvikns) [reply src/messages.tsx:13]: @derberg I was making these changes, and I think It would look good if the command example has a different color, but it is hard to make them in different colors in a string. But as we are using ink I think making all the text messages a component would be nice.

Comment (derberg) [reply src/messages.tsx:13]: yup, definitely, one of the reasons we use Ink. I guess that you would prefer to do it in a followup PR to not complicate this one?

Comment (Souvikns) [reply src/messages.tsx:13]: Ok so in this PR I will just keep it as it is and update the texts. Then in another follow-up pr, we can convert all string constants to components.

File: src/messages.tsx (hunk 6 above)
Comment (Souvikns) [reply src/messages.tsx:11]: This is used when any input variables are missing 

https://github.com/asyncapi/cli/blob/2f69e066f00c1dcb8336b1f1f2d8aac09d23884b/src/hooks/context/models.ts#L50-L55

File: src/messages.tsx (hunk 4 above)
Comment (Souvikns) [reply src/messages.tsx:7]: This one is currently not in use. I created it for a warning case if the user is deleting any context that is set as current but didn't end up using it. Should I remove this?

Comment (derberg) [reply src/messages.tsx:7]: yup

File: src/messages.tsx (hunk 6 above)
Comment (derberg) [reply src/messages.tsx:11]: let's leave it as it is for now

**Comment by derberg** [comment]
ready for last review round?

**Comment by Souvikns** [comment]
Two minor things left to update, then It will be ready.

**Comment by Souvikns** [comment]
> ready for last review round?

@derberg I am ready for the last review round. 🤞🏻

**Review by derberg — COMMENTED** [review]
one more message left

```
export class SpecFileNotFoundError extends Error {
  constructor() {
    super();
    this.message = 'specification file not found in that path.';
  }
}
```

should be `No AsyncAPI file found in {PATH}`

best reuse message from validation, `File: ${filePath} does not exists or is not a file!`

File: src/messages.tsx [hunk 8]
```diff
@@ -0,0 +1,16 @@
+export const NO_CONTEXTS_SAVED = 'No contexts saved yet, run asyncapi --help to learn more';
+
+export const CONTEXT_NOT_FOUND = (contextName: string) => `Context ${contextName} does not exists.`;
+
+export const MISSING_CURRENT_CONTEXT = 'No context is set as current, please set a current context.';
+
+export const MISSING_ARGUMENTS = 'Missing arguments.';
+
+export const NEW_CONTEXT_ADDED = (contextName: string) => `New context added.\nYou can set it as your current context:\n asyncapi context use ${contextName}\nYou can use this context when needed with --context flag`;
```
Comment (derberg) [inline src/messages.tsx:9]:
```suggestion
export const NEW_CONTEXT_ADDED = (contextName: string) => `New context added.\n\nYou can set it as your current context: asyncapi context use ${contextName}\nYou can use this context when needed with --context flag: asyncapi validate --context ${contextName}`;
```

**Review by derberg — COMMENTED** [review]
left just 2 comments and additional question: meow should be updated and use new help message right?
