### PR TITLE
fix: add v3 checks for all commands

### LINKED ISSUE #629: AsyncAPI spec v3 support in CLI
### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

Potentially, disable certain commands if they don't support v3.

### Scope

- [x] https://github.com/asyncapi/parser-js/issues/780
- [x] https://github.com/asyncapi/modelina/issues/1376
- [x] https://github.com/asyncapi/generator/issues/979
- [x] https://github.com/asyncapi/bundler/issues/133
- [x] https://github.com/asyncapi/diff/issues/154
- [x] https://github.com/asyncapi/optimizer/issues/168
- [x] https://github.com/asyncapi/studio/issues/641
- [x] https://github.com/asyncapi/cupid/issues/171
- [x] https://github.com/asyncapi/converter-js/issues/110
- [ ] Update all dependencies once they suppport v3

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR adds v3 checks for most commands, and give an error if the command does not support v3:
- bundle 
- diff, when one of the files are v3
- generate fromTemplate, when the template is a specific one:
  - @asyncapi/html-template
  - @asyncapi/dotnet-nats-template
  - @asyncapi/ts-nats-template
  - @asyncapi/python-paho-template
  - @asyncapi/nodejs-ws-template
  - @asyncapi/java-spring-cloud-stream-template
  - @asyncapi/go-watermill-template
  - @asyncapi/java-spring-template
  - @asyncapi/markdown-template
- generate models
- optimize
- validate

I left out the following commands, because I don't think they are relevant to shelter:
- convert (already supports v3)
- glee (has it's own runtime)
- studio (has it's own runtime)

It does so by peaking into the spec document and checking the `asyncapi` property.

These checks are only temporary and another approach in the future is probably needed as discussed in #629, but this change is to ensure CLI is ready whenever v3 is released.

**Related issue(s)**
Related to #629

### CODE REVIEW

File: src/commands/generate/fromTemplate.ts [hunk 1]
```diff
@@ -99,14 +122,21 @@ export default class Template extends Command {
...
       genOption.resolve = {resolve: this.getMapBaseUrlToFolderResolver(parsedFlags.mapBaseUrlToFolder)};
     }
 
-    await this.generate(asyncapi, template, output, options, genOption);    
+    if (asyncapiInput.isAsyncAPI3()) {
+      const v3IssueLink = verifyTemplateSupportForV3(template);
+      if (v3IssueLink !== undefined) {
+        this.error(`${template} template does not support AsyncAPI v3 documents, please checkout ${v3IssueLink}`);
+      }
+    }
```
Comment (Souvikns) [inline src/commands/generate/fromTemplate.ts:138]: what happens when I pass in a custom template that does not support v3?

Comment (jonaslagoni) [reply src/commands/generate/fromTemplate.ts:138]: Nothing, we cant expect the unexpected 🙂 

Custom templates can easily be added to the list of templates that don't support v3, so all about contributing 😄

Comment (Souvikns) [reply src/commands/generate/fromTemplate.ts:138]: > Nothing, we cant expect the unexpected 🙂

Yeah, that make sense. 

I was thinking that since templates have a config in the `package.json` they might have a parameter that could help us determine which spec versions this template supports, but now that I have checked I don't think there is anything like that.

**Review by Souvikns — APPROVED** [review]
LGTM, just had that one doubt

**Comment by jonaslagoni** [comment]
Not really up to me, it's your folks repo, I am just suggesting a change like any other contributor @Souvikns 😄 

But if you say go ahead and merge then I wont stop 😄

File: src/commands/generate/fromTemplate.ts [hunk 2]
```diff
@@ -30,6 +30,29 @@ interface ParsedFlags {
...
+  '@asyncapi/minimaltemplate': 'some link', // For testing purpose
+  '@asyncapi/html-template': 'https://github.com/asyncapi/html-template/issues/430',
+  '@asyncapi/dotnet-nats-template': 'https://github.com/asyncapi/dotnet-nats-template/issues/384',
+  '@asyncapi/ts-nats-template': 'https://github.com/asyncapi/ts-nats-template/issues/545',
+  '@asyncapi/python-paho-template': 'https://github.com/asyncapi/python-paho-template/issues/189',
+  '@asyncapi/nodejs-ws-template': 'https://github.com/asyncapi/nodejs-ws-template/issues/294',
+  '@asyncapi/java-spring-cloud-stream-template': 'https://github.com/asyncapi/java-spring-cloud-stream-template/issues/336',
+  '@asyncapi/go-watermill-template': 'https://github.com/asyncapi/go-watermill-template/issues/243',
+  '@asyncapi/java-spring-template': 'https://github.com/asyncapi/java-spring-template/issues/308',
+  '@asyncapi/markdown-template': 'https://github.com/asyncapi/markdown-template/issues/341'
```
Comment (derberg) [inline src/commands/generate/fromTemplate.ts:43]: we are missing:
- @asyncapi/nodejs-template
- @asyncapi/java-template
- @asyncapi/php-template

Comment (jonaslagoni) [reply src/commands/generate/fromTemplate.ts]: I have missed php-template completely, nice catch 👍

Comment (jonaslagoni) [reply src/commands/generate/fromTemplate.ts]: Added 👍

**Review by derberg — APPROVED** [review]
lgtm

@Souvikns need another approval. Once you approve, just merge

**Review by Souvikns — APPROVED** [review]
