### PR TITLE
fix: made studio start on different port if one is already in use

### LINKED ISSUE #1797: [ENHANCEMENT] Allow starting of other instance of studio if one is already running.
### Why do we need this improvement?

Currently if `asyncapi studio` is running and one tries to start another instance of studio with a different file the command is stuck if different ports are not passed manually and no message is displayed.

### How will this change help?

Will allow opening of multiple instance of `studio` for different files.

### Screenshots

Image

### How could it be implemented/designed?

Allow trying of different ports if not passed manually.

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [x] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by neoandmatrix**
**Description**

The PR adds the functionality to automatically start a new instance of studio on a different port if the current port intended to be used is already in use.

image

An info is displayed that the specified port was already in use hence a different port is being used to the user.

**Related issue(s)**
Resolves #1797

### CODE REVIEW

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Comment by neoandmatrix** [comment]
Hey @AayushSaini101 @Shurtu-gal if possible can this be reviewed and merged as #1824 is dependent on this.

Thanks

**Comment by neoandmatrix** [comment]
Hey @AayushSaini101 @Shurtu-gal any update on this ?

**Comment by Shurtu-gal** [comment]
I guess we should not go ahead with this iterative checking of ports. Can use stuff like: https://expressjs.com/en/api.html#app.listen

Basically mentioning port as 0 gets the OS to allocate a port.

**Comment by neoandmatrix** [comment]
> I guess we should not go ahead with this iterative checking of ports. Can use stuff like: https://expressjs.com/en/api.html#app.listen

Is this specific to express.js? I believe we are not using express.

And also it might cause inconsistency as OS will always assign a random port with this method not only for case if port is already in use.

**Comment by Shurtu-gal** [comment]
We are using nodejs http which has the same functionality.

**Comment by neoandmatrix** [comment]
Okay but assigning a random port every time , would it be a good practice and experience ? Also it will make testing harder i believe.

**Comment by neoandmatrix** [comment]
One concern for me with the random port approach is testing these commands through puppeteer. As we need to navigate to the url for testing and since we include port in the url query parameters it being random would make it extremely difficult to navigate that site and test the instance as url would be random every time.

 Inferring it from logs is extremely difficult as it would require a lot of parsing which make tests un-reliable.

Passing the port through flag is also not possible as we can only pass strings in parameter in tests but port require a number which cannot be passed.

**Comment by neoandmatrix** [comment]
Hey @Shurtu-gal with respect to above discussion how should i proceed with this ?

**Comment by Shurtu-gal** [comment]
I suppose we can wait for @AayushSaini101 or @Souvikns input also.

**Comment by AayushSaini101** [comment]
> https://expressjs.com/en/api.html#app.listen

> I guess we should not go ahead with this iterative checking of ports. Can use stuff like: https://expressjs.com/en/api.html#app.listen
> 
> Basically mentioning port as 0 gets the OS to allocate a port.

I guess we can go for iterating port allocation to the server, explicitly allocating the port is not a proper way, wdyt @Souvikns

**Comment by Shurtu-gal** [comment]
> I guess we can go for iterating port allocation to the server

Setting up server and checking each port is not the way to go according to me.

> explicitly allocating the port is not a proper way

I couldn't understand this.

**Comment by aeworxet** [comment]
`npm install portfinder` installs four packages and takes 1.3 MB.
Are these quantities and size a significant concern in this case?

```
$ ls
async
debug
ms
portfinder

$ du -h
32K	./debug/src
68K	./debug
444K	./async/dist
112K	./async/internal
1.1M	./async
20K	./ms
24K	./portfinder/lib
40K	./portfinder
1.3M	.
```

**Comment by aeworxet** [comment]
@Souvikns, do you have insights on https://github.com/asyncapi/cli/pull/1815#issuecomment-3139798032 ?

The package `portfinder`, presumably, can easily resolve this issue, but as I understand it, @Shurtu-gal is not very certain about iterating the ports, and I was addressing https://github.com/asyncapi/cli/issues/1752 with the question of whether the quantity and size of the packages are concerning.

**Comment by neoandmatrix** [comment]
@Shurtu-gal would it be a problem if the custom port passed using the -p flag can be taken as a string instead of number and necessary checks are added that the passed port is within the correct port range of allowed ports on a device and is an postive integer. 

Internally then we convert it to a number and pass it to the studio commands and for other cases we pass 0 to allocate an available port as suggested by you.

As for the UX of the user there would be no changes.

If this is good it would allow me resolve both this issue and #1693.

**Comment by Shurtu-gal** [comment]
Yep @neoandmatrix I would like to back this approach. Let's wait for @AayushSaini101 and @Souvikns thoughts as well.

**Comment by Shurtu-gal** [comment]
> passed port is within the correct port range of allowed ports on a device and is a positive integer.

Can check if the port is being used as well I suppose.

**Comment by neoandmatrix** [comment]
> Can check if the port is being used as well I suppose.

Yes but it would require setting up a temporary server. Would that be fine?

**Comment by Shurtu-gal** [comment]
Won't starting studio also show the `EADDRINUSE` error. We can utilise that I suppose. 

Also I will be resolving the conflicts in evening, a new architecture has been Implemented.

**Comment by neoandmatrix** [comment]
> Won't starting studio also show the EADDRINUSE error. We can utilise that I suppose.

Yes it would but only after server has tried starting up once and it would throw the error in .catch() only from where starting the server i believe is not possible only error message can be displayed to user.

**Comment by Shurtu-gal** [comment]
> Yes it would but only after server has tried starting up once and it would throw the error in .catch() only from where starting the server i believe is not possible only error message can be displayed to user.

If user is explicitly defining the port only error message should suffice.

**Comment by neoandmatrix** [comment]
Sure then it can be done.

**Comment by neoandmatrix** [comment]
@AayushSaini101 @Souvikns can you please have a look at the new suggested approach for resolution of this issue and let me know if i should proceed with the changes for same or not?

Thanks.

**Comment by neoandmatrix** [comment]
@Shurtu-gal let me update this PR with the new approach and then we can discuss from there on as this has been unfortunately delayed too much.

**Comment by neoandmatrix** [comment]
Hey @Shurtu-gal i have updated the PR with new approach and everything seems to be working fine and as expected. Only this linter in testing is failing. Can you please have a look at the new changes?

Thanks.

**Comment by aeworxet** [comment]
When the code is working not only fine but also as expected, it's a relief for the developer.

File: src/apps/cli/commands/start/preview.ts [hunk 1]
```diff
@@ -23,7 +23,9 @@ export default class PreviewStudio extends Command {
 
     let filePath: string | undefined = args['spec-file'] ?? flags.file;
 
-    const previewPort = flags.port;
+    const previewPort = parseInt(flags.port ?? '0',10);
+
+    // to add : add check here
```
Comment (Shurtu-gal) [inline src/apps/cli/commands/start/preview.ts:28]: Anything else you wish to add here?

**Comment by Shurtu-gal** [comment]
> Only this linter in testing is failing. Can you please have a look at the new changes?

The changes are looking fine by me. I believe you would be integrating these changes into the tests as well?

Regarding linter: fixing this https://github.com/asyncapi/cli/blob/7817c6d672679f26096d0a99f48b5a7015ceee1c/src/utils/temp-dir.ts#L13-L16 should work.

**Comment by neoandmatrix** [comment]
> The changes are looking fine by me. I believe you would be integrating these changes into the tests as well?

In studio testing yes these will be added but not random port allocation as that will be done by OS so I don't think that's needed to be tested explicitly or separately.

**Comment by neoandmatrix** [comment]
Hey @AayushSaini101 @Shurtu-gal have resolved all the error and tests are also passing now. Can you please have a look?

Thanks
